/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Connexion.Connection;
import buttonProg.INSERT;
import java.awt.Toolkit;
import java.sql.Statement;
/**
 *
 * @author Y.T
 */
public class Ajouter_prof extends javax.swing.JFrame {

    /**
     * Creates new form Ajouter_prof
     */
    public Ajouter_prof() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        nom = new javax.swing.JTextField();
        prenom = new javax.swing.JTextField();
        cin = new javax.swing.JTextField();
        lieu_naissance = new javax.swing.JTextField();
        date_de_naissance = new javax.swing.JTextField();
        situation_famillial = new javax.swing.JTextField();
        specialite = new javax.swing.JTextField();
        date_recrutement = new javax.swing.JTextField();
        grade = new javax.swing.JTextField();
        somme = new javax.swing.JTextField();
        cadre = new javax.swing.JTextField();
        echellon = new javax.swing.JTextField();
        Situation_admin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Enregistrer");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 490, -1, -1));

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Annuler");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 490, -1, -1));

        nom.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        nom.setForeground(new java.awt.Color(102, 102, 102));
        nom.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nom.setText("Nom");
        nom.setPreferredSize(new java.awt.Dimension(6, 25));
        nom.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nomFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nomFocusLost(evt);
            }
        });
        getContentPane().add(nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 200, 30));

        prenom.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        prenom.setForeground(new java.awt.Color(102, 102, 102));
        prenom.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        prenom.setText("Prenom");
        prenom.setPreferredSize(new java.awt.Dimension(6, 25));
        prenom.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                prenomMouseDragged(evt);
            }
        });
        prenom.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                prenomFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                prenomFocusLost(evt);
            }
        });
        getContentPane().add(prenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 200, 30));

        cin.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        cin.setForeground(new java.awt.Color(102, 102, 102));
        cin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cin.setText("CIN");
        cin.setPreferredSize(new java.awt.Dimension(6, 25));
        cin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cinFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cinFocusLost(evt);
            }
        });
        getContentPane().add(cin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 200, 30));

        lieu_naissance.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        lieu_naissance.setForeground(new java.awt.Color(102, 102, 102));
        lieu_naissance.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lieu_naissance.setText("Lieu de Naissance");
        lieu_naissance.setPreferredSize(new java.awt.Dimension(6, 25));
        lieu_naissance.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lieu_naissanceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lieu_naissanceFocusLost(evt);
            }
        });
        getContentPane().add(lieu_naissance, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 200, 30));

        date_de_naissance.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        date_de_naissance.setForeground(new java.awt.Color(102, 102, 102));
        date_de_naissance.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        date_de_naissance.setText("Date de Naissance");
        date_de_naissance.setPreferredSize(new java.awt.Dimension(6, 25));
        date_de_naissance.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                date_de_naissanceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                date_de_naissanceFocusLost(evt);
            }
        });
        getContentPane().add(date_de_naissance, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 200, 30));

        situation_famillial.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        situation_famillial.setForeground(new java.awt.Color(102, 102, 102));
        situation_famillial.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        situation_famillial.setText("Situation Famillial");
        situation_famillial.setPreferredSize(new java.awt.Dimension(6, 25));
        situation_famillial.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                situation_famillialFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                situation_famillialFocusLost(evt);
            }
        });
        getContentPane().add(situation_famillial, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 200, 30));

        specialite.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        specialite.setForeground(new java.awt.Color(102, 102, 102));
        specialite.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        specialite.setText("Specialitee");
        specialite.setPreferredSize(new java.awt.Dimension(6, 25));
        specialite.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                specialiteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                specialiteFocusLost(evt);
            }
        });
        getContentPane().add(specialite, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 190, 30));

        date_recrutement.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        date_recrutement.setForeground(new java.awt.Color(102, 102, 102));
        date_recrutement.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        date_recrutement.setText("Date recrutement");
        date_recrutement.setPreferredSize(new java.awt.Dimension(6, 25));
        date_recrutement.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                date_recrutementFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                date_recrutementFocusLost(evt);
            }
        });
        getContentPane().add(date_recrutement, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 190, 30));

        grade.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        grade.setForeground(new java.awt.Color(102, 102, 102));
        grade.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        grade.setText("Grade");
        grade.setPreferredSize(new java.awt.Dimension(6, 25));
        grade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                gradeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                gradeFocusLost(evt);
            }
        });
        getContentPane().add(grade, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 190, 30));

        somme.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        somme.setForeground(new java.awt.Color(102, 102, 102));
        somme.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        somme.setText("Numero_Some");
        somme.setPreferredSize(new java.awt.Dimension(6, 25));
        somme.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                sommeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                sommeFocusLost(evt);
            }
        });
        getContentPane().add(somme, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 190, 30));

        cadre.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        cadre.setForeground(new java.awt.Color(102, 102, 102));
        cadre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cadre.setText("Cadre");
        cadre.setPreferredSize(new java.awt.Dimension(6, 25));
        cadre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cadreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cadreFocusLost(evt);
            }
        });
        getContentPane().add(cadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, 190, 30));

        echellon.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        echellon.setForeground(new java.awt.Color(102, 102, 102));
        echellon.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        echellon.setText("Echellon");
        echellon.setPreferredSize(new java.awt.Dimension(6, 25));
        echellon.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                echellonFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                echellonFocusLost(evt);
            }
        });
        getContentPane().add(echellon, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 190, 30));

        Situation_admin.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        Situation_admin.setForeground(new java.awt.Color(102, 102, 102));
        Situation_admin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Situation_admin.setText("Situation Administarive");
        Situation_admin.setPreferredSize(new java.awt.Dimension(6, 25));
        Situation_admin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Situation_adminFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Situation_adminFocusLost(evt);
            }
        });
        getContentPane().add(Situation_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 250, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/FPO logo1_2.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 410, 90));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/min.png"))); // NOI18N
        jLabel5.setToolTipText("Minimize");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 12, 20, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/exi1.png"))); // NOI18N
        jLabel4.setToolTipText("Close");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 20, 20));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Login1.png"))); // NOI18N
        jLabel15.setPreferredSize(new java.awt.Dimension(300, 200));
        jLabel15.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel15MouseDragged(evt);
            }
        });
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel15MousePressed(evt);
            }
        });
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
         Connection connect;
     
      try{  
        connect = new Connection();
        Statement stmt = connect.con.createStatement();
  if(!nom.getText().isEmpty() && !nom.getText().isEmpty() && !prenom.getText().isEmpty() && !somme.getText().isEmpty()&& !cin.getText().isEmpty() && !grade.getText().isEmpty() && !cadre.getText().isEmpty() && !lieu_naissance.getText().isEmpty() && !date_de_naissance.getText().isEmpty() && !situation_famillial.getText().isEmpty() && !date_recrutement.getText().isEmpty() && !echellon.getText().isEmpty() && !specialite.getText().isEmpty() && !Situation_admin.getText().isEmpty()){
     String infoPresonnes[]={nom.getText(),prenom.getText(), somme.getText(), cin.getText(), grade.getText(),cadre.getText(),"prof"};
      String infoPersonnels[]={lieu_naissance.getText(),date_de_naissance.getText(),situation_famillial.getText(), date_recrutement.getText(), echellon.getText(), specialite.getText(), Situation_admin.getText(),"prof"};
      String AJoutePersonne[]={"NOM","PRENOM","SOM","CIN","GRADE","CADRE","type"};
     String AJoutePersonnels[]={"LIEU_DE_NAISSANCE","DATE_NAISSANCE","SITUATION_FAMILIALE","DATE_RECRUTMENT","ECHELON","SEPCIALITE","SITUATION_ADMINISTRATIVE","type"};
                  //
          INSERT in=new INSERT();
    String SQL=in.queryInsert("infopersonnes", AJoutePersonne, infoPresonnes);
 
     String SQL2=in.queryInsert("infopersonnels", AJoutePersonnels, infoPersonnels);
       stmt.executeUpdate(SQL);
   stmt.executeUpdate(SQL2);
       System.out.print("c fais");
       infoPersonnels=null;
       infoPresonnes=null;
 } 
  else{
 System.out.print("veuillez entrer tous les informations pour contunier");
  }
 }catch(Exception ex){
          System.out.print("Ereur");
      }
      interProf ip = new interProf();
      ip.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        interProf ip = new interProf();
        ip.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       this.setLocation(Toolkit.getDefaultToolkit().getScreenSize().width / 2 - 260, Toolkit.getDefaultToolkit().getScreenSize().height / 2 - 300);
    }//GEN-LAST:event_formWindowOpened
int x,y;
    private void jLabel15MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MousePressed
  x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jLabel15MousePressed

    private void jLabel15MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseDragged
       this.setLocation((int) evt.getXOnScreen() - x, (int) evt.getYOnScreen() - y);
    }//GEN-LAST:event_jLabel15MouseDragged

    private void nomFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomFocusGained
        if(nom.getText().equalsIgnoreCase("Nom"))
            nom.setText(null);
    }//GEN-LAST:event_nomFocusGained

    private void nomFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomFocusLost
       if(nom.getText().isEmpty())
        nom.setText("Nom");
  
    }//GEN-LAST:event_nomFocusLost

    private void prenomMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prenomMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_prenomMouseDragged

    private void prenomFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_prenomFocusGained
       if(prenom.getText().equalsIgnoreCase("Prenom"))
            prenom.setText(null);
    }//GEN-LAST:event_prenomFocusGained

    private void prenomFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_prenomFocusLost
        if(prenom.getText().isEmpty())
        prenom.setText("Prenom");
    }//GEN-LAST:event_prenomFocusLost

    private void cinFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cinFocusGained
           if(cin.getText().equalsIgnoreCase("CIN"))
            cin.setText(null);
    }//GEN-LAST:event_cinFocusGained

    private void cinFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cinFocusLost
        if(cin.getText().isEmpty())
        cin.setText("CIN");
    }//GEN-LAST:event_cinFocusLost

    private void lieu_naissanceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lieu_naissanceFocusGained
        if(lieu_naissance.getText().equalsIgnoreCase("Lieu de Naissance"))
            lieu_naissance.setText(null);
    }//GEN-LAST:event_lieu_naissanceFocusGained

    private void lieu_naissanceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lieu_naissanceFocusLost
         if(lieu_naissance.getText().isEmpty())
        lieu_naissance.setText("Lieu de Naissance");
    }//GEN-LAST:event_lieu_naissanceFocusLost

    private void date_de_naissanceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_date_de_naissanceFocusGained
     if(date_de_naissance.getText().equalsIgnoreCase("Date de Naissance"))
            date_de_naissance.setText(null);
    }//GEN-LAST:event_date_de_naissanceFocusGained

    private void date_de_naissanceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_date_de_naissanceFocusLost
     if(date_de_naissance.getText().isEmpty())
        date_de_naissance.setText("Date de Naissance");
    }//GEN-LAST:event_date_de_naissanceFocusLost

    private void situation_famillialFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_situation_famillialFocusGained
    if(situation_famillial.getText().equalsIgnoreCase("Situation Famillial"))
            situation_famillial.setText(null);
    }//GEN-LAST:event_situation_famillialFocusGained

    private void situation_famillialFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_situation_famillialFocusLost
          if(situation_famillial.getText().isEmpty())
        situation_famillial.setText("Situation Famillial");
    }//GEN-LAST:event_situation_famillialFocusLost

    private void specialiteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_specialiteFocusGained
    if(specialite.getText().equalsIgnoreCase("Specialitee"))
            specialite.setText(null);
    }//GEN-LAST:event_specialiteFocusGained

    private void specialiteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_specialiteFocusLost
        if(specialite.getText().isEmpty())
        specialite.setText("Specialitee");
    }//GEN-LAST:event_specialiteFocusLost

    private void date_recrutementFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_date_recrutementFocusGained
    if(date_recrutement.getText().equalsIgnoreCase("Date Recrutement"))
            date_recrutement.setText(null);
    }//GEN-LAST:event_date_recrutementFocusGained

    private void date_recrutementFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_date_recrutementFocusLost
        if(date_recrutement.getText().isEmpty())
        date_recrutement.setText("Date Recrutement");
    }//GEN-LAST:event_date_recrutementFocusLost

    private void gradeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_gradeFocusGained
    if(grade.getText().equalsIgnoreCase("Grade"))
            grade.setText(null);
    }//GEN-LAST:event_gradeFocusGained

    private void gradeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_gradeFocusLost
        if(grade.getText().isEmpty())
        grade.setText("Grade");
    }//GEN-LAST:event_gradeFocusLost

    private void sommeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sommeFocusGained
       if(somme.getText().equalsIgnoreCase("Numero_Some"))
            somme.setText(null);
    }//GEN-LAST:event_sommeFocusGained

    private void sommeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sommeFocusLost
         if(somme.getText().isEmpty())
        somme.setText("Numero_Some");
    }//GEN-LAST:event_sommeFocusLost

    private void echellonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_echellonFocusGained
     if(echellon.getText().equalsIgnoreCase("Echellon"))
            echellon.setText(null);
    }//GEN-LAST:event_echellonFocusGained

    private void echellonFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_echellonFocusLost
      if(echellon.getText().isEmpty())
        echellon.setText("Echellon");
    }//GEN-LAST:event_echellonFocusLost

    private void cadreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cadreFocusGained
        if(cadre.getText().equalsIgnoreCase("Cadre"))
            cadre.setText(null);
    }//GEN-LAST:event_cadreFocusGained

    private void cadreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cadreFocusLost
        if(cadre.getText().isEmpty())
        cadre.setText("Cadre");
    }//GEN-LAST:event_cadreFocusLost

    private void Situation_adminFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Situation_adminFocusGained
        if(Situation_admin.getText().equalsIgnoreCase("Situation Administarive"))
            Situation_admin.setText(null);
    }//GEN-LAST:event_Situation_adminFocusGained

    private void Situation_adminFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Situation_adminFocusLost
        if(Situation_admin.getText().isEmpty())
        Situation_admin.setText("Situation Administarive");
    }//GEN-LAST:event_Situation_adminFocusLost

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered

    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ajouter_prof.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ajouter_prof.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ajouter_prof.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ajouter_prof.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ajouter_prof().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Situation_admin;
    private javax.swing.JTextField cadre;
    private javax.swing.JTextField cin;
    private javax.swing.JTextField date_de_naissance;
    private javax.swing.JTextField date_recrutement;
    private javax.swing.JTextField echellon;
    private javax.swing.JTextField grade;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField lieu_naissance;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField prenom;
    private javax.swing.JTextField situation_famillial;
    private javax.swing.JTextField somme;
    private javax.swing.JTextField specialite;
    // End of variables declaration//GEN-END:variables
}
