/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Connexion.Connection;
import buttonProg.INSERT;
import java.awt.Toolkit;
import java.sql.Statement;

/**
 *
 * @author mounir
 */
public class Ajouter_emp extends javax.swing.JFrame {

    /**
     * Creates new form Ajouter_emp
     */
    public Ajouter_emp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nom = new javax.swing.JTextField();
        prenom = new javax.swing.JTextField();
        nomar = new javax.swing.JTextField();
        prenomar = new javax.swing.JTextField();
        sex = new javax.swing.JTextField();
        cin = new javax.swing.JTextField();
        date_recrutement = new javax.swing.JTextField();
        date_de_naissance = new javax.swing.JTextField();
        situation_famillial = new javax.swing.JTextField();
        Date_affectation = new javax.swing.JTextField();
        grade = new javax.swing.JTextField();
        echellon = new javax.swing.JTextField();
        echelle = new javax.swing.JTextField();
        som = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nom.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        nom.setForeground(new java.awt.Color(102, 102, 102));
        nom.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nom.setText("Nom");
        nom.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nomFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nomFocusLost(evt);
            }
        });
        nom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nomMouseClicked(evt);
            }
        });
        nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomActionPerformed(evt);
            }
        });
        getContentPane().add(nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 200, -1));

        prenom.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        prenom.setForeground(new java.awt.Color(102, 102, 102));
        prenom.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        prenom.setText("Prenom");
        prenom.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                prenomFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                prenomFocusLost(evt);
            }
        });
        getContentPane().add(prenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 200, -1));

        nomar.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        nomar.setForeground(new java.awt.Color(102, 102, 102));
        nomar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nomar.setText("الاسم الشخصي");
        nomar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nomarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nomarFocusLost(evt);
            }
        });
        getContentPane().add(nomar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 200, -1));

        prenomar.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        prenomar.setForeground(new java.awt.Color(102, 102, 102));
        prenomar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        prenomar.setText("الاسم العائلي");
        prenomar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                prenomarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                prenomarFocusLost(evt);
            }
        });
        getContentPane().add(prenomar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 200, -1));

        sex.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        sex.setForeground(new java.awt.Color(102, 102, 102));
        sex.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sex.setText("Sex");
        sex.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                sexFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                sexFocusLost(evt);
            }
        });
        getContentPane().add(sex, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 200, -1));

        cin.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        cin.setForeground(new java.awt.Color(102, 102, 102));
        cin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cin.setText("Cin");
        cin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cinFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cinFocusLost(evt);
            }
        });
        getContentPane().add(cin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 200, -1));

        date_recrutement.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        date_recrutement.setForeground(new java.awt.Color(102, 102, 102));
        date_recrutement.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        date_recrutement.setText("Date Recrutement");
        date_recrutement.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                date_recrutementFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                date_recrutementFocusLost(evt);
            }
        });
        getContentPane().add(date_recrutement, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 200, -1));

        date_de_naissance.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        date_de_naissance.setForeground(new java.awt.Color(102, 102, 102));
        date_de_naissance.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        date_de_naissance.setText("Date de Naissance");
        date_de_naissance.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                date_de_naissanceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                date_de_naissanceFocusLost(evt);
            }
        });
        date_de_naissance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date_de_naissanceActionPerformed(evt);
            }
        });
        getContentPane().add(date_de_naissance, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 200, -1));

        situation_famillial.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        situation_famillial.setForeground(new java.awt.Color(102, 102, 102));
        situation_famillial.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        situation_famillial.setText("Situation Familial");
        situation_famillial.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                situation_famillialFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                situation_famillialFocusLost(evt);
            }
        });
        getContentPane().add(situation_famillial, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 200, -1));

        Date_affectation.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        Date_affectation.setForeground(new java.awt.Color(102, 102, 102));
        Date_affectation.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Date_affectation.setText("Date d'affectation");
        Date_affectation.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Date_affectationFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Date_affectationFocusLost(evt);
            }
        });
        getContentPane().add(Date_affectation, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 200, -1));

        grade.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        grade.setForeground(new java.awt.Color(102, 102, 102));
        grade.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        grade.setText("Grade");
        grade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                gradeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                gradeFocusLost(evt);
            }
        });
        getContentPane().add(grade, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 200, -1));

        echellon.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        echellon.setForeground(new java.awt.Color(102, 102, 102));
        echellon.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        echellon.setText("Echellon");
        echellon.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                echellonFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                echellonFocusLost(evt);
            }
        });
        getContentPane().add(echellon, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 200, -1));

        echelle.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        echelle.setForeground(new java.awt.Color(102, 102, 102));
        echelle.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        echelle.setText("Echelle");
        echelle.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                echelleFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                echelleFocusLost(evt);
            }
        });
        getContentPane().add(echelle, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 200, -1));

        som.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        som.setForeground(new java.awt.Color(102, 102, 102));
        som.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        som.setText("Numero_Som");
        som.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                somFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                somFocusLost(evt);
            }
        });
        getContentPane().add(som, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, 200, -1));

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Enregistrer");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 410, -1, -1));

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Annuler");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 410, 85, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/FPO logo1_2.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 410, 90));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/min.png"))); // NOI18N
        jLabel14.setToolTipText("Minimize");
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 12, 20, 20));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/exi1.png"))); // NOI18N
        jLabel15.setToolTipText("Close");
        jLabel15.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel15MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel15MousePressed(evt);
            }
        });
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, 20, 20));

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Login1.png"))); // NOI18N
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomActionPerformed

    private void date_de_naissanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date_de_naissanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date_de_naissanceActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        Connection connect;
     
      try{  
        connect = new Connection();
        Statement stmt = connect.con.createStatement();
  if(!nom.getText().isEmpty() && !prenom.getText().isEmpty() && !nomar.getText().isEmpty() && !sex.getText().isEmpty() && !cin.getText().isEmpty() && !date_de_naissance.getText().isEmpty() && !situation_famillial.getText().isEmpty() && !date_recrutement.getText().isEmpty() && !Date_affectation.getText().isEmpty() && !grade.getText().isEmpty() && !echelle.getText().isEmpty() && !echellon.getText().isEmpty() && !som.getText().isEmpty()){
     String infoPresonnes[]={nom.getText(),prenom.getText(), cin.getText(), grade.getText(), som.getText(),"emp"};
     String infoPersonnels[]={nomar.getText(),prenomar.getText(),sex.getText(),date_de_naissance.getText(),situation_famillial.getText(), date_recrutement.getText(),Date_affectation.getText(),echelle.getText(),echellon.getText(),"emp"};
      String AJoutePersonne[]={"NOM","PRENOM","CIN","GRADE","SOM","type"};
     String AJoutePersonnels[]={"NOMAR","PRENOMAR","SEX","DATE_NAISSANCE","SITUATION_FAMILIALE","DATE_RECRUTMENT","Date_affectation","ECHELLE","ECHELON","type"};
                  
          INSERT in=new INSERT();
   String SQL=in.queryInsert("infopersonnes", AJoutePersonne, infoPresonnes);
 
     String SQL2=in.queryInsert("infopersonnels", AJoutePersonnels, infoPersonnels);
      stmt.executeUpdate(SQL);
  stmt.executeUpdate(SQL2);
       System.out.print("c fais");
       //infoPersonnels=null;
       //infoPresonnes=null;
 } 
  else{
 System.out.print("veuillez entrer tous les informations pour contunier");
  }
 }catch(Exception ex){
          System.out.print("Ereur");
      }
      
    new interemploi().setVisible(true);
    this.dispose();
    
    }//GEN-LAST:event_jButton1MouseClicked

    private void nomFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomFocusGained
 if(nom.getText().equalsIgnoreCase("Nom"))
            nom.setText(null);
    }//GEN-LAST:event_nomFocusGained

    private void nomFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomFocusLost
        if(nom.getText().isEmpty())
        nom.setText("Nom");
    }//GEN-LAST:event_nomFocusLost

    private void nomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nomMouseClicked
       if(nom.getText().equalsIgnoreCase("Nom"))
            nom.setText(null);
    }//GEN-LAST:event_nomMouseClicked

    private void prenomFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_prenomFocusGained
         if(prenom.getText().equalsIgnoreCase("Prenom"))
            prenom.setText(null);
    }//GEN-LAST:event_prenomFocusGained

    private void prenomFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_prenomFocusLost
            if(prenom.getText().isEmpty())
               prenom.setText("Prenom");
    }//GEN-LAST:event_prenomFocusLost

    private void nomarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomarFocusGained
          if(nomar.getText().equalsIgnoreCase("الاسم الشخصي"))
            nomar.setText(null);
    }//GEN-LAST:event_nomarFocusGained

    private void nomarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomarFocusLost
            if(nomar.getText().isEmpty())
               nomar.setText("الاسم الشخصي");
    }//GEN-LAST:event_nomarFocusLost

    private void prenomarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_prenomarFocusGained
        if(prenomar.getText().equalsIgnoreCase("الاسم العائلي"))
            prenomar.setText(null);
    }//GEN-LAST:event_prenomarFocusGained

    private void prenomarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_prenomarFocusLost
        if(prenomar.getText().isEmpty())
               prenomar.setText("الاسم العائلي");
    }//GEN-LAST:event_prenomarFocusLost

    private void sexFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sexFocusGained
        if(sex.getText().equalsIgnoreCase("Sex"))
            sex.setText(null);
    }//GEN-LAST:event_sexFocusGained

    private void sexFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sexFocusLost
        if(sex.getText().isEmpty())
              sex.setText("Sex");
    }//GEN-LAST:event_sexFocusLost

    private void cinFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cinFocusGained
         if(cin.getText().equalsIgnoreCase("Cin"))
            cin.setText(null);
    }//GEN-LAST:event_cinFocusGained

    private void cinFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cinFocusLost
         if(cin.getText().isEmpty())
              cin.setText("Cin");
    }//GEN-LAST:event_cinFocusLost

    private void date_recrutementFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_date_recrutementFocusGained
        if(date_recrutement.getText().equalsIgnoreCase("Date Recrutement"))
            date_recrutement.setText(null);
    }//GEN-LAST:event_date_recrutementFocusGained

    private void date_recrutementFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_date_recrutementFocusLost
       if(date_recrutement.getText().isEmpty())
              date_recrutement.setText("Date Recrutement");
    }//GEN-LAST:event_date_recrutementFocusLost

    private void date_de_naissanceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_date_de_naissanceFocusGained
         if(date_de_naissance.getText().equalsIgnoreCase("Date de Naissance"))
            date_de_naissance.setText(null);
    }//GEN-LAST:event_date_de_naissanceFocusGained

    private void date_de_naissanceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_date_de_naissanceFocusLost
        if(date_de_naissance.getText().isEmpty())
              date_de_naissance.setText("Date de Naissance");
    }//GEN-LAST:event_date_de_naissanceFocusLost

    private void situation_famillialFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_situation_famillialFocusGained
       if(situation_famillial.getText().equalsIgnoreCase("Situation Familial"))
            situation_famillial.setText(null);
    }//GEN-LAST:event_situation_famillialFocusGained

    private void situation_famillialFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_situation_famillialFocusLost
       if(situation_famillial.getText().isEmpty())
              situation_famillial.setText("Situation Familial");
    }//GEN-LAST:event_situation_famillialFocusLost

    private void Date_affectationFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Date_affectationFocusGained
          if(Date_affectation.getText().equalsIgnoreCase("Date d'affectation"))
            Date_affectation.setText(null);
    }//GEN-LAST:event_Date_affectationFocusGained

    private void Date_affectationFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Date_affectationFocusLost
      if(Date_affectation.getText().isEmpty())
              Date_affectation.setText("Date d'affectation");
    }//GEN-LAST:event_Date_affectationFocusLost

    private void gradeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_gradeFocusGained
       if(grade.getText().equalsIgnoreCase("Grade"))
            grade.setText(null);
    }//GEN-LAST:event_gradeFocusGained

    private void gradeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_gradeFocusLost
        if(grade.getText().isEmpty())
              grade.setText("Grade");
    }//GEN-LAST:event_gradeFocusLost

    private void echellonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_echellonFocusGained
         if(echellon.getText().equalsIgnoreCase("Echellon"))
            echellon.setText(null);
    }//GEN-LAST:event_echellonFocusGained

    private void echellonFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_echellonFocusLost
         if(echellon.getText().isEmpty())
              echellon.setText("Echellon");
    }//GEN-LAST:event_echellonFocusLost

    private void echelleFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_echelleFocusGained
         if(echelle.getText().equalsIgnoreCase("Echelle"))
            echelle.setText(null);
    }//GEN-LAST:event_echelleFocusGained

    private void echelleFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_echelleFocusLost
    if(echelle.getText().isEmpty())
              echelle.setText("Echelle");
    }//GEN-LAST:event_echelleFocusLost

    private void somFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_somFocusGained
         if(som.getText().equalsIgnoreCase("Numero_Som"))
            som.setText(null);
    }//GEN-LAST:event_somFocusGained

    private void somFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_somFocusLost
           if(som.getText().isEmpty())
              som.setText("Numero_Som");
    }//GEN-LAST:event_somFocusLost

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        interemploi ie = new interemploi();
        ie.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseEntered

    }//GEN-LAST:event_jLabel15MouseEntered

    private void jLabel15MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel15MousePressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
                this.setLocation(Toolkit.getDefaultToolkit().getScreenSize().width / 2 - 290, Toolkit.getDefaultToolkit().getScreenSize().height / 2 - 300);
    }//GEN-LAST:event_formWindowOpened
        int x,y;   
    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        this.setLocation((int) evt.getXOnScreen() - x, (int) evt.getYOnScreen() - y);
    }//GEN-LAST:event_jLabel1MouseDragged

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jLabel1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ajouter_emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ajouter_emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ajouter_emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ajouter_emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ajouter_emp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Date_affectation;
    private javax.swing.JTextField cin;
    private javax.swing.JTextField date_de_naissance;
    private javax.swing.JTextField date_recrutement;
    private javax.swing.JTextField echelle;
    private javax.swing.JTextField echellon;
    private javax.swing.JTextField grade;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField nomar;
    private javax.swing.JTextField prenom;
    private javax.swing.JTextField prenomar;
    private javax.swing.JTextField sex;
    private javax.swing.JTextField situation_famillial;
    private javax.swing.JTextField som;
    // End of variables declaration//GEN-END:variables
}
