/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Connexion.Connection;
import static Interface.interemploi.temtab;
import buttonProg.INSERT;
import java.awt.Toolkit;
import java.sql.Statement;

/**
 *
 * @author mounir
 */
public class modifier_emp extends javax.swing.JFrame {

    /**
     * Creates new form Ajouter_emp
     */
    public modifier_emp() {
        initComponents();
        nom.setText(interemploi.temtab[0]);
        prenom.setText(interemploi.temtab[1]);
       cin.setText(interemploi.temtab[5]);
       nomar.setText(interemploi.temtab[2]);
       prenomar.setText(interemploi.temtab[3]);
       date_de_naissance.setText(interemploi.temtab[6]);
       situation_famillial.setText(interemploi.temtab[7]);
       som.setText(interemploi.temtab[13]);
       date_recrutement.setText(interemploi.temtab[8]);
       grade.setText(interemploi.temtab[10]);
       sex.setText(interemploi.temtab[4]);
       Date_affectation.setText(interemploi.temtab[9]);
       echellon.setText(interemploi.temtab[12]);
       echelle.setText(interemploi.temtab[11]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        prenom = new javax.swing.JTextField();
        nomar = new javax.swing.JTextField();
        prenomar = new javax.swing.JTextField();
        sex = new javax.swing.JTextField();
        cin = new javax.swing.JTextField();
        date_recrutement = new javax.swing.JTextField();
        date_de_naissance = new javax.swing.JTextField();
        situation_famillial = new javax.swing.JTextField();
        Date_affectation = new javax.swing.JTextField();
        grade = new javax.swing.JTextField();
        echellon = new javax.swing.JTextField();
        echelle = new javax.swing.JTextField();
        som = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nom");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 158, -1, -1));

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Prenom");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 195, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("الاسم الشخصي");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 238, -1, -1));

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Echellon");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, -1, -1));

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Grade:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, -1, -1));

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Date d'affectation:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, -1, -1));

        jLabel7.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Situation Familial:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("الاسم العائلي");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 281, -1, -1));

        jLabel9.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Date de Naissance:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, -1, -1));

        jLabel10.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Sex:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 324, -1, -1));

        jLabel11.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Cin:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 367, -1, -1));

        jLabel12.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Echelle");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, -1, -1));

        jLabel13.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Date Recrutement:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 410, -1, -1));

        jLabel14.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Som");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 410, -1, -1));

        nom.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        nom.setPreferredSize(new java.awt.Dimension(8, 25));
        nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomActionPerformed(evt);
            }
        });
        getContentPane().add(nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 231, -1));

        prenom.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        prenom.setPreferredSize(new java.awt.Dimension(8, 25));
        getContentPane().add(prenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 231, -1));

        nomar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        nomar.setPreferredSize(new java.awt.Dimension(8, 25));
        getContentPane().add(nomar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 231, -1));

        prenomar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        prenomar.setPreferredSize(new java.awt.Dimension(8, 25));
        getContentPane().add(prenomar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 231, -1));

        sex.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        sex.setPreferredSize(new java.awt.Dimension(8, 25));
        getContentPane().add(sex, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 231, -1));

        cin.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        cin.setPreferredSize(new java.awt.Dimension(8, 25));
        getContentPane().add(cin, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 231, -1));

        date_recrutement.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        date_recrutement.setPreferredSize(new java.awt.Dimension(8, 25));
        getContentPane().add(date_recrutement, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, 231, -1));

        date_de_naissance.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        date_de_naissance.setPreferredSize(new java.awt.Dimension(8, 25));
        date_de_naissance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date_de_naissanceActionPerformed(evt);
            }
        });
        getContentPane().add(date_de_naissance, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 147, 231, -1));

        situation_famillial.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        situation_famillial.setPreferredSize(new java.awt.Dimension(8, 25));
        getContentPane().add(situation_famillial, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 190, 231, -1));

        Date_affectation.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        Date_affectation.setPreferredSize(new java.awt.Dimension(8, 25));
        getContentPane().add(Date_affectation, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 233, 231, -1));

        grade.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        grade.setPreferredSize(new java.awt.Dimension(8, 25));
        getContentPane().add(grade, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 276, 231, -1));

        echellon.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        echellon.setPreferredSize(new java.awt.Dimension(8, 25));
        getContentPane().add(echellon, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 319, 231, -1));

        echelle.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        echelle.setPreferredSize(new java.awt.Dimension(8, 25));
        getContentPane().add(echelle, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 362, 231, -1));

        som.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        som.setPreferredSize(new java.awt.Dimension(8, 25));
        getContentPane().add(som, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 405, 231, -1));

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Enregistrer");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 490, -1, -1));

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Annuler");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 490, 85, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/FPO logo1_2.png"))); // NOI18N
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, 90));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/exi1.png"))); // NOI18N
        jLabel16.setToolTipText("Close");
        jLabel16.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel16MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel16MousePressed(evt);
            }
        });
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 10, 20, 20));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/min.png"))); // NOI18N
        jLabel17.setToolTipText("Minimize");
        jLabel17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 12, 20, 20));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Login_ajou.png"))); // NOI18N
        jLabel15.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel15MouseDragged(evt);
            }
        });
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel15MousePressed(evt);
            }
        });
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomActionPerformed

    private void date_de_naissanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date_de_naissanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date_de_naissanceActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        Connection connect;
     
      try{  
        
             connect = new Connection();
        Statement stmt = connect.con.createStatement();
          String sql4="DELETE FROM `infopersonnes` WHERE NOM='"+temtab[0]+"'and PRENOM='"+temtab[1]+"'and GRADE='"+temtab[10]+"'and SOM='"+temtab[13]+"' and CIN='"+temtab[5]+"'";
         String sql3="DELETE FROM `infopersonnels` WHERE NOMAR='"+temtab[2]+"'and PRENOMAR='"+temtab[3]+"'and SEX='"+temtab[4]+"'and DATE_NAISSANCE='"+temtab[5]+"'and SITUATION_FAMILIALE='"+temtab[6]+"' and DATE_RECRUTMENT='"+temtab[7]+"' and Date_affectation='"+temtab[8]+"' and ECHELLE='"+temtab[9]+"' and ECHELON='"+temtab[10]+"'";
   
          stmt.executeUpdate(sql4);
          stmt.executeUpdate(sql3);
           System.out.println("c fais");
 
  if(!nom.getText().isEmpty() && !prenom.getText().isEmpty() && !nomar.getText().isEmpty() && !sex.getText().isEmpty() && !cin.getText().isEmpty() && !date_de_naissance.getText().isEmpty() && !situation_famillial.getText().isEmpty() && !date_recrutement.getText().isEmpty() && !Date_affectation.getText().isEmpty() && !grade.getText().isEmpty() && !echelle.getText().isEmpty() && !echellon.getText().isEmpty() && !som.getText().isEmpty()){
     String infoPresonnes[]={nom.getText(),prenom.getText(), cin.getText(), grade.getText(), som.getText(),"emp"};
     String infoPersonnels[]={nomar.getText(),prenomar.getText(),sex.getText(),date_de_naissance.getText(),situation_famillial.getText(), date_recrutement.getText(),Date_affectation.getText(),echelle.getText(),echellon.getText(),"emp"};
      String AJoutePersonne[]={"NOM","PRENOM","CIN","GRADE","SOM","type"};
     String AJoutePersonnels[]={"NOMAR","PRENOMAR","SEX","DATE_NAISSANCE","SITUATION_FAMILIALE","DATE_RECRUTMENT","Date_affectation","ECHELLE","ECHELON","type"};
                  
          INSERT in=new INSERT();
   String SQL=in.queryInsert("infopersonnes", AJoutePersonne, infoPresonnes);
 
     String SQL2=in.queryInsert("infopersonnels", AJoutePersonnels, infoPersonnels);
      stmt.executeUpdate(SQL);
  stmt.executeUpdate(SQL2);
       System.out.print("c fais");
       this.dispose();
        interemploi i =new interemploi ();
     i.setVisible(true);
 } 
  else{
 System.out.print("veuillez entrer tous les informations pour contunier");
  }
 
 }catch(Exception ex){
          System.out.print("Ereur");
      }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseEntered

    }//GEN-LAST:event_jLabel16MouseEntered

    private void jLabel16MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel16MousePressed

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        interemploi em = new interemploi();
        em.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
            this.setLocation(Toolkit.getDefaultToolkit().getScreenSize().width / 2 - 260, Toolkit.getDefaultToolkit().getScreenSize().height / 2 - 300);
    }//GEN-LAST:event_formWindowOpened
int x,y;
    private void jLabel15MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseDragged
        this.setLocation((int) evt.getXOnScreen() - x, (int) evt.getYOnScreen() - y);
    }//GEN-LAST:event_jLabel15MouseDragged

    private void jLabel15MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jLabel15MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modifier_emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modifier_emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modifier_emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modifier_emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new modifier_emp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Date_affectation;
    private javax.swing.JTextField cin;
    private javax.swing.JTextField date_de_naissance;
    private javax.swing.JTextField date_recrutement;
    private javax.swing.JTextField echelle;
    private javax.swing.JTextField echellon;
    private javax.swing.JTextField grade;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField nomar;
    private javax.swing.JTextField prenom;
    private javax.swing.JTextField prenomar;
    private javax.swing.JTextField sex;
    private javax.swing.JTextField situation_famillial;
    private javax.swing.JTextField som;
    // End of variables declaration//GEN-END:variables
}
