
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Image;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Rectangle;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import static java.awt.image.ImageObserver.ALLBITS;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.SQLException;
import java.text.SimpleDateFormat;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Y.T
 */
public class imprimer extends javax.swing.JFrame {

   private String text;
   private String text2;
   private String article1;
    public imprimer() {
        text="   Je soussigné, Belahsen Youness, Doyen de la Faculté Polydisciplinaire de Ouarzazate  atteste que Monsieur:  \n" +
"           - NOM         :     	\n" +
"           - PRENOM :     \n" +
"           - CIN           :    \n" +
"           - D.R.P.P     :   \n" +
"           \n" +
"Exerce la fonction d’administrateur 3 éme grade  au sein de notre établissement depuis le.\n" +"\n"

                    + "      Cette attestation est délivrée à l’intéressé(e) pour servir et valoir ce que de droit.\n\n";
        text2="Le Doyen de la Faculté  Polydisciplinaire Ouarzazate :\n" +
"- Vu le Dahir  n°1.58.008 du 04 chaâbane 1377 (24 février 1958) portant statut général de la fonction publique tel qu’il a été modifié et complété.\n" +
"- Vu la demande présentée par l’intéressée.  ";
        article1="";
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("OK");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Conjee");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jButton1)
                .addGap(58, 58, 58)
                .addComponent(jButton2)
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(193, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
       openPDF();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
      conje();
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
public void openPDF() {
    Rectangle layout = new Rectangle(PageSize.A4.rotate());
   layout.setBorderColor(BaseColor.BLACK);
   layout.setBorderWidth(10);      //Border width  
   layout.setBorder(Rectangle.BOX); 
        Document document = new Document(layout);
        try {
            PdfWriter.getInstance(document, new FileOutputStream("imprimer test.pdf"));
            
            document.open();
            Image image = Image.getInstance("logofpo.png");
            image.setAlignment(Image.MIDDLE);
            document.add(image);
            SimpleDateFormat td = new SimpleDateFormat("dd-MM-yyyy");
            java.util.Date now = new java.util.Date();
            String tdnow = td.format(now);  
            Paragraph pa = new Paragraph("Attestation de travail", FontFactory.getFont(FontFactory.TIMES, 30, Font.UNDERLINE, BaseColor.DARK_GRAY));
            pa.setAlignment(Paragraph.ALIGN_CENTER);
            document.add(pa);
            for(int i=0;i<3;i++){
                document.add(new Paragraph(" "));
            }
            
            Paragraph p = new Paragraph(text, FontFactory.getFont(FontFactory.TIMES, 18, Font.NORMAL, BaseColor.DARK_GRAY));
            document.add(p);
            
            Paragraph time = new Paragraph("                Fait à Ouarzazate le : "+tdnow,FontFactory.getFont(FontFactory.TIMES, 17, Font.BOLD, BaseColor.DARK_GRAY));
            Paragraph a = new Paragraph("");
            Paragraph si = new Paragraph("                 Signature:",FontFactory.getFont(FontFactory.TIMES, 17, Font.BOLD, BaseColor.DARK_GRAY));

            time.setAlignment(Paragraph.ALIGN_CENTER);
            si.setAlignment(Paragraph.ALIGN_CENTER);
            document.add(time);
            document.add(si);
            document.add(a);
            document.close();
            
             System.out.println("date2");
            /* Open Pdf */
            Desktop desktop = Desktop.getDesktop();
            if (desktop.isSupported(Desktop.Action.OPEN)) {
                desktop.open(new File("imprimer test.pdf"));
            } else {
                System.out.println("Open is not supported");
            }
             
             System.out.println("date");
        } catch (Exception ex) {
            
        System.out.println("qsdqs");
        }
    }

public void conje() {
    Rectangle layout = new Rectangle(PageSize.A4.rotate());
   layout.setBorderColor(BaseColor.BLACK);
   layout.setBorderWidth(10);      //Border width  
   layout.setBorder(Rectangle.BOX); 
        Document document = new Document(layout);
        try {
            PdfWriter.getInstance(document, new FileOutputStream("conjee.pdf"));
            
            document.open();
            Image image = Image.getInstance("logofpo.png");
            image.setAlignment(Image.MIDDLE);
            document.add(image);
            SimpleDateFormat td = new SimpleDateFormat("dd-MM-yyyy");
            java.util.Date now = new java.util.Date();
            String tdnow = td.format(now);  
            Paragraph pa = new Paragraph("Décision de congé", FontFactory.getFont(FontFactory.TIMES, 20, Font.UNDERLINE, BaseColor.DARK_GRAY));
            pa.setAlignment(Paragraph.ALIGN_CENTER);
            document.add(pa);
            for(int i=0;i<1;i++){
                document.add(new Paragraph(" "));
            }
            
            Paragraph p = new Paragraph(text2, FontFactory.getFont(FontFactory.TIMES, 15, Font.NORMAL, BaseColor.DARK_GRAY));
            document.add(p);
             Paragraph p3 = new Paragraph("DECIDE :", FontFactory.getFont(FontFactory.TIMES, 15, Font.BOLD, BaseColor.DARK_GRAY));
                         p3.setAlignment(Paragraph.ALIGN_CENTER);
            document.add(p3);
             Paragraph p4 = new Paragraph("ARTICLE I Un congé d’un .", FontFactory.getFont(FontFactory.TIMES, 15, Font.BOLDITALIC, BaseColor.DARK_GRAY));
            document.add(p4);
            Paragraph p5 = new Paragraph(
"           Est accordé à   :    \n" +
"           C.I.N           :    \n" +
"           GRADE           :    \n" +
"           Pour la période :   ", FontFactory.getFont(FontFactory.TIMES, 15, Font.NORMAL, BaseColor.DARK_GRAY));
            document.add(p5);
  Paragraph p6 = new Paragraph("ARTICLE II", FontFactory.getFont(FontFactory.TIMES, 16, Font.BOLDITALIC, BaseColor.DARK_GRAY));
            document.add(p6);
            Paragraph p7 = new Paragraph("L’intéressé(e) est autorisé à quitter le territoire national durant la période indiquée ci-dessus", FontFactory.getFont(FontFactory.TIMES, 18, Font.NORMAL, BaseColor.DARK_GRAY));
            document.add(p7);
              Paragraph p8 = new Paragraph("ARTICLE III", FontFactory.getFont(FontFactory.TIMES, 16, Font.BOLDITALIC, BaseColor.DARK_GRAY));
            document.add(p8);
            Paragraph p9 = new Paragraph("L’intéressé(e) est tenu d’aviser le service du personnel de sa reprise de travail après expiration du  congé sus-visé.", FontFactory.getFont(FontFactory.TIMES, 18, Font.NORMAL, BaseColor.DARK_GRAY));
            document.add(p9);
            
             Paragraph av = new Paragraph("");
            
            Paragraph time = new Paragraph("                                         Cachet et signature                                                                       Fait à Ouarzazate le : "+tdnow,FontFactory.getFont(FontFactory.TIMES, 14, Font.BOLD, BaseColor.DARK_GRAY));
            Paragraph a = new Paragraph("");
            Paragraph si = new Paragraph("                                                                                                                                     Signature du  demandeur",FontFactory.getFont(FontFactory.TIMES, 14, Font.BOLD, BaseColor.DARK_GRAY));

            time.setAlignment(Paragraph.ALIGN_LEFT);
            si.setAlignment(Paragraph.ALIGN_CENTER);
            document.add(time);
            document.add(si);
            document.add(a);
            document.add(av);
            document.close();
            
             System.out.println("date2");
            /* Open Pdf */
            Desktop desktop = Desktop.getDesktop();
            if (desktop.isSupported(Desktop.Action.OPEN)) {
                desktop.open(new File("conjee.pdf"));
            } else {
                System.out.println("Open is not supported");
            }
             
             System.out.println("date");
        } catch (Exception ex) {
            
        System.out.println("qsdqs");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(imprimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(imprimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(imprimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(imprimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new imprimer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
